/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{signal_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Alert */
        post: operations["confirm_alert_api_v1_alerts__signal_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report */
        post: operations["create_report_api_v1_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report */
        get: operations["export_report_api_v1_reports__report_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screenings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screenings */
        post: operations["screenings_api_v1_screenings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{market}/{stock_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Detail */
        get: operations["stock_detail_api_v1_stocks__market___stock_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{market}/{stock_code}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Indicators */
        get: operations["stock_indicators_api_v1_stocks__market___stock_code__indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{market}/{stock_code}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Prices */
        get: operations["stock_prices_api_v1_stocks__market___stock_code__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{market}/{stock_code}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Signals */
        get: operations["stock_signals_api_v1_stocks__market___stock_code__signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sync Job */
        post: operations["create_sync_job_api_v1_sync_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sync Job */
        get: operations["get_sync_job_api_v1_sync_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Items */
        get: operations["watchlist_items_api_v1_watchlist_items_get"];
        put?: never;
        /** Create Watchlist Item */
        post: operations["create_watchlist_item_api_v1_watchlist_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist Item */
        delete: operations["delete_watchlist_item_api_v1_watchlist_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertItem */
        AlertItem: {
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Rule Code */
            rule_code: string;
            /** Status */
            status: string;
            /** Stock Code */
            stock_code: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** AlertListResponse */
        AlertListResponse: {
            /** Batch Id */
            batch_id: number;
            /** Items */
            items: components["schemas"]["AlertItem"][];
            /** Rule Version */
            rule_version: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** AlertStateResponse */
        AlertStateResponse: {
            /** Confirmed At */
            confirmed_at: string | null;
            /** Id */
            id: number;
            /** Status */
            status: string;
        };
        /** BatchContext */
        BatchContext: {
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** CandidateItem */
        CandidateItem: {
            /** Market */
            market: string;
            /** Reasons */
            reasons: string[];
            /** Score */
            score: number;
            /** Stock Code */
            stock_code: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Batch Id */
            batch_id: number;
            /** Candidates */
            candidates: components["schemas"]["CandidateItem"][];
            /** Completeness Rate */
            completeness_rate: number;
            market_summary: components["schemas"]["MarketSummary"];
            /** Rule Version */
            rule_version: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** IndicatorSeriesResponse */
        IndicatorSeriesResponse: {
            /** Batch Id */
            batch_id: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Rule Version */
            rule_version: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** MarketSummary */
        MarketSummary: {
            /** Amount */
            amount: number;
            /** Down */
            down: number;
            /** Flat */
            flat: number;
            /** Up */
            up: number;
        };
        /** PriceItem */
        PriceItem: {
            /** Adjustment */
            adjustment: string;
            /** Amount */
            amount: number;
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Pct Change */
            pct_change: number | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Turnover Rate */
            turnover_rate: number | null;
            /** Volume */
            volume: number;
        };
        /** PriceSeriesResponse */
        PriceSeriesResponse: {
            /** Batch Id */
            batch_id: number;
            /** Items */
            items: components["schemas"]["PriceItem"][];
            /** Rule Version */
            rule_version: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** ReportRequest */
        ReportRequest: {
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Batch Id */
            batch_id: number;
            /** Content */
            content: string;
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Report Version */
            report_version: number;
            /** Rule Version */
            rule_version: string;
            /** Stock Code */
            stock_code: string;
            /** Template Version */
            template_version: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** ScreeningRequest */
        ScreeningRequest: {
            /**
             * Minimum Score
             * @default 0
             */
            minimum_score: number;
        };
        /** ScreeningResponse */
        ScreeningResponse: {
            /** Batch Id */
            batch_id: number;
            /** Items */
            items: components["schemas"]["CandidateItem"][];
            /** Rule Version */
            rule_version: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** SignalItem */
        SignalItem: {
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Rule Code */
            rule_code: string;
            /** Stock Code */
            stock_code: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** SignalSeriesResponse */
        SignalSeriesResponse: {
            /** Batch Id */
            batch_id: number;
            /** Items */
            items: components["schemas"]["SignalItem"][];
            /** Rule Version */
            rule_version: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** StockDetailResponse */
        StockDetailResponse: {
            /** Batch Id */
            batch_id: number;
            /** Market */
            market: string;
            price: components["schemas"]["PriceItem"] | null;
            /** Rule Version */
            rule_version: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** SyncCreatedResponse */
        SyncCreatedResponse: {
            /** Batch Id */
            batch_id: number;
            /** Job Id */
            job_id: number;
        };
        /** SyncJobResponse */
        SyncJobResponse: {
            /** Completed Count */
            completed_count: number;
            /** Error Summary */
            error_summary: string | null;
            /** Failed Count */
            failed_count: number;
            /** Id */
            id: number;
            /** Progress */
            progress: number;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Target Trade Date */
            target_trade_date: string | null;
        };
        /** SyncRequest */
        SyncRequest: {
            /**
             * Target Trade Date
             * Format: date
             */
            target_trade_date: string;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            active_batch: components["schemas"]["BatchContext"] | null;
            latest_sync: components["schemas"]["SyncJobResponse"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistItemResponse */
        WatchlistItemResponse: {
            /** Group Id */
            group_id: number;
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Note */
            note: string | null;
            /** Stock Code */
            stock_code: string;
        };
        /** WatchlistRequest */
        WatchlistRequest: {
            /** Group Id */
            group_id: number;
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /** Items */
            items: components["schemas"]["WatchlistItemResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
        };
    };
    confirm_alert_api_v1_alerts__signal_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_report_api_v1_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_v1_reports__report_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screenings_api_v1_screenings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreeningRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_detail_api_v1_stocks__market___stock_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_indicators_api_v1_stocks__market___stock_code__indicators_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_prices_api_v1_stocks__market___stock_code__prices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_signals_api_v1_stocks__market___stock_code__signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sync_job_api_v1_sync_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sync_job_api_v1_sync_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    watchlist_items_api_v1_watchlist_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
        };
    };
    create_watchlist_item_api_v1_watchlist_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_item_api_v1_watchlist_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
