/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai-recommendations/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Ai Recommendations */
        post: operations["import_ai_recommendations_api_v1_ai_recommendations_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sync Job */
        post: operations["create_sync_job_api_v1_sync_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Sync Job */
        post: operations["retry_sync_job_api_v1_sync_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sync Job */
        get: operations["get_sync_job_api_v1_sync_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-batches/{batch_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Data Batch */
        post: operations["activate_data_batch_api_v1_data_batches__batch_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{market}/{stock_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Detail */
        get: operations["stock_detail_api_v1_stocks__market___stock_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{market}/{stock_code}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Prices */
        get: operations["stock_prices_api_v1_stocks__market___stock_code__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{market}/{stock_code}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Indicators */
        get: operations["stock_indicators_api_v1_stocks__market___stock_code__indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{market}/{stock_code}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Signals */
        get: operations["stock_signals_api_v1_stocks__market___stock_code__signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screenings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screenings */
        post: operations["screenings_api_v1_screenings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Items */
        get: operations["watchlist_items_api_v1_watchlist_items_get"];
        put?: never;
        /** Create Watchlist Item */
        post: operations["create_watchlist_item_api_v1_watchlist_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watchlist Groups */
        get: operations["watchlist_groups_api_v1_watchlist_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist Item */
        delete: operations["delete_watchlist_item_api_v1_watchlist_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{signal_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Alert */
        post: operations["confirm_alert_api_v1_alerts__signal_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report */
        post: operations["create_report_api_v1_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report */
        get: operations["export_report_api_v1_reports__report_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_v1_screener_presets_get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_api_v1_screener_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener-presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Preset */
        delete: operations["delete_preset_api_v1_screener_presets__preset_id__delete"];
        options?: never;
        head?: never;
        /** Update Preset */
        patch: operations["update_preset_api_v1_screener_presets__preset_id__patch"];
        trace?: never;
    };
    "/api/v1/screener-presets/{preset_id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Default Preset */
        post: operations["default_preset_api_v1_screener_presets__preset_id__default_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_api_v1_decision_notes_get"];
        put?: never;
        /** Create Note */
        post: operations["create_note_api_v1_decision_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note */
        delete: operations["delete_note_api_v1_decision_notes__note_id__delete"];
        options?: never;
        head?: never;
        /** Update Note */
        patch: operations["update_note_api_v1_decision_notes__note_id__patch"];
        trace?: never;
    };
    "/api/v1/decision-notes/{note_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Note */
        post: operations["restore_note_api_v1_decision_notes__note_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rule Version */
        post: operations["create_rule_version_api_v1_rule_versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alert Rules */
        get: operations["list_alert_rules_api_v1_alert_rules_get"];
        put?: never;
        /** Create Alert Rule */
        post: operations["create_alert_rule_api_v1_alert_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-rules/{logical_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Alert Rule */
        delete: operations["delete_alert_rule_api_v1_alert_rules__logical_id__delete"];
        options?: never;
        head?: never;
        /** Update Alert Rule */
        patch: operations["update_alert_rule_api_v1_alert_rules__logical_id__patch"];
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_settings_patch"];
        trace?: never;
    };
    "/api/v1/realtime/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_realtime_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/realtime/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_realtime_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/realtime/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quotes */
        get: operations["quotes_api_v1_realtime_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outcomes */
        get: operations["list_outcomes_api_v1_strategy_outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/outcomes/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summarize Outcomes */
        get: operations["summarize_outcomes_api_v1_strategy_outcomes_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/outcomes/{candidate_result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate Outcomes */
        get: operations["candidate_outcomes_api_v1_strategy_outcomes__candidate_result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/outcome-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Outcome Run */
        post: operations["create_outcome_run_api_v1_strategy_outcome_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/outcome-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outcome Run */
        get: operations["get_outcome_run_api_v1_strategy_outcome_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIRecommendationImportRequest */
        AIRecommendationImportRequest: {
            /** Batch Id */
            batch_id: number;
            /**
             * Scope
             * @default candidate
             * @enum {string}
             */
            scope: "candidate" | "watchlist";
            /**
             * Provider
             * @constant
             */
            provider: "codex_cli";
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Evidence Snapshot */
            evidence_snapshot: {
                [key: string]: unknown;
            };
            /** Items */
            items: components["schemas"]["AIRecommendationItemImport"][];
        };
        /** AIRecommendationImportResponse */
        AIRecommendationImportResponse: {
            /** Batch Id */
            batch_id: number;
            /** Imported Count */
            imported_count: number;
            /** Run Id */
            run_id: number;
        };
        /** AIRecommendationItem */
        AIRecommendationItem: {
            /**
             * Recommendation
             * @enum {string}
             */
            recommendation: "FOCUS" | "WATCH" | "AVOID";
            /** Ai Score */
            ai_score: number;
            /**
             * Horizon Trading Days
             * @enum {integer}
             */
            horizon_trading_days: 1 | 3 | 5;
            /** Reasons */
            reasons: string[];
            /** Risks */
            risks: string[];
            /** Invalidation */
            invalidation: string;
            /** Confidence */
            confidence: number;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Run Version */
            run_version: number;
        };
        /** AIRecommendationItemImport */
        AIRecommendationItemImport: {
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /**
             * Recommendation
             * @enum {string}
             */
            recommendation: "FOCUS" | "WATCH" | "AVOID";
            /** Ai Score */
            ai_score: number;
            /**
             * Horizon Trading Days
             * @enum {integer}
             */
            horizon_trading_days: 1 | 3 | 5;
            /** Reasons */
            reasons: string[];
            /** Risks */
            risks: string[];
            /** Invalidation */
            invalidation: string;
            /** Confidence */
            confidence: number;
        };
        /** AlertItem */
        AlertItem: {
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Rule Code */
            rule_code: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
        };
        /** AlertListResponse */
        AlertListResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Items */
            items: components["schemas"]["AlertItem"][];
        };
        /** AlertRuleList */
        AlertRuleList: {
            /** Items */
            items: components["schemas"]["AlertRuleResponse"][];
        };
        /** AlertRuleRequest */
        AlertRuleRequest: {
            /** Name */
            name: string;
            /** Rule Code */
            rule_code: string;
            /** Threshold */
            threshold: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** AlertRuleResponse */
        AlertRuleResponse: {
            /** Name */
            name: string;
            /** Rule Code */
            rule_code: string;
            /** Threshold */
            threshold: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: number;
            /** Logical Id */
            logical_id: number;
            /** Version */
            version: number;
        };
        /** AlertRuleUpdate */
        AlertRuleUpdate: {
            /** Threshold */
            threshold: number;
            /** Enabled */
            enabled: boolean;
        };
        /** AlertStateResponse */
        AlertStateResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Confirmed At */
            confirmed_at: string | null;
        };
        /** BatchActivationRequest */
        BatchActivationRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** BatchActivationResponse */
        BatchActivationResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Completeness Rate */
            completeness_rate: number;
        };
        /** BatchContext */
        BatchContext: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
        };
        /** CandidateItem */
        CandidateItem: {
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name?: string | null;
            /** Score */
            score: number;
            /** Reasons */
            reasons: string[];
            /** Close */
            close?: number | null;
            /** Pct Change */
            pct_change?: number | null;
            /** Rsi14 */
            rsi14?: number | null;
            /** Volume Ratio */
            volume_ratio?: number | null;
            /**
             * Outcome Status
             * @default PENDING
             * @enum {string}
             */
            outcome_status: "PENDING" | "PARTIAL" | "COMPLETED" | "UNAVAILABLE";
            ai_recommendation?: components["schemas"]["AIRecommendationItem"] | null;
        };
        /** CandidateOutcomes */
        CandidateOutcomes: {
            /** Items */
            items: components["schemas"]["StrategyOutcomeView"][];
            /** Calculation Version */
            calculation_version: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Completeness Rate */
            completeness_rate: number;
            /** Candidates */
            candidates: components["schemas"]["CandidateItem"][];
            market_summary: components["schemas"]["MarketSummary"] | null;
            /** Indices */
            indices: components["schemas"]["IndexItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Api Version */
            api_version: string;
        };
        /** IndexItem */
        IndexItem: {
            /** Index Code */
            index_code: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Close */
            close: number;
            /** Pct Change */
            pct_change: number | null;
        };
        /** IndicatorSeriesResponse */
        IndicatorSeriesResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
        };
        /** MarketSummary */
        MarketSummary: {
            /** Up */
            up: number;
            /** Down */
            down: number;
            /** Flat */
            flat: number;
            /** Amount */
            amount: number;
        };
        /** NoteList */
        NoteList: {
            /** Items */
            items: components["schemas"]["NoteResponse"][];
        };
        /** NoteRequest */
        NoteRequest: {
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Content */
            content: string;
        };
        /** NoteResponse */
        NoteResponse: {
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Content */
            content: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
        };
        /** NoteUpdate */
        NoteUpdate: {
            /** Content */
            content: string;
        };
        /** OutcomeRunCreateRequest */
        OutcomeRunCreateRequest: {
            /** Evaluation Batch Id */
            evaluation_batch_id: number;
        };
        /** OutcomeRunResponse */
        OutcomeRunResponse: {
            /** Id */
            id: number;
            /** Evaluation Batch Id */
            evaluation_batch_id: number;
            /** Calculation Version */
            calculation_version: string;
            /** Status */
            status: string;
            /** Expected Count */
            expected_count: number;
            /** Completed Count */
            completed_count: number;
            /** Unavailable Count */
            unavailable_count: number;
            /** Pending Count */
            pending_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error Summary */
            error_summary: string | null;
        };
        /** PresetList */
        PresetList: {
            /** Items */
            items: components["schemas"]["PresetResponse"][];
        };
        /** PresetRequest */
        PresetRequest: {
            /** Name */
            name: string;
            /** Conditions */
            conditions: {
                [key: string]: unknown;
            };
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** PresetResponse */
        PresetResponse: {
            /** Name */
            name: string;
            /** Conditions */
            conditions: {
                [key: string]: unknown;
            };
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Id */
            id: number;
        };
        /** PresetUpdate */
        PresetUpdate: {
            /** Name */
            name?: string | null;
            /** Conditions */
            conditions?: {
                [key: string]: unknown;
            } | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /** PriceItem */
        PriceItem: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Adjustment */
            adjustment: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /** Amount */
            amount: number;
            /** Pct Change */
            pct_change: number | null;
            /** Turnover Rate */
            turnover_rate: number | null;
            /** Is Suspended */
            is_suspended: boolean;
        };
        /** PriceSeriesResponse */
        PriceSeriesResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Items */
            items: components["schemas"]["PriceItem"][];
        };
        /** RealtimeJobResponse */
        RealtimeJobResponse: {
            /** Id */
            id: number;
            /**
             * Scope
             * @default watchlist
             * @constant
             */
            scope: "watchlist";
            /**
             * Status
             * @enum {string}
             */
            status: "FETCHING" | "READY" | "PARTIAL" | "FAILED";
            /** Stage */
            stage: string;
            /** Total Count */
            total_count: number;
            /** Completed Count */
            completed_count: number;
            /** Failed Count */
            failed_count: number;
            /** Error Summary */
            error_summary: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** RealtimeQuoteResponse */
        RealtimeQuoteResponse: {
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name: string;
            /** Latest Price */
            latest_price: number | null;
            /** Pct Change */
            pct_change: number | null;
            /** Volume */
            volume: number;
            /** Amount */
            amount: number;
            /**
             * Quoted At
             * Format: date-time
             */
            quoted_at: string;
        };
        /** RealtimeQuotesResponse */
        RealtimeQuotesResponse: {
            snapshot: components["schemas"]["RealtimeSnapshotResponse"] | null;
            /** Items */
            items: components["schemas"]["RealtimeQuoteResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** RealtimeSnapshotResponse */
        RealtimeSnapshotResponse: {
            /** Refresh Id */
            refresh_id: number;
            /**
             * Scope
             * @default watchlist
             * @constant
             */
            scope: "watchlist";
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /**
             * Quote Date
             * Format: date
             */
            quote_date: string;
            /** Total Count */
            total_count: number;
            /** Received Count */
            received_count: number;
            /** Missing Count */
            missing_count: number;
            /** Missing Symbols */
            missing_symbols: string[];
            /** Stale Count */
            stale_count: number;
            /** Unavailable Count */
            unavailable_count: number;
            market_summary: components["schemas"]["MarketSummary"];
        };
        /** RealtimeStatusResponse */
        RealtimeStatusResponse: {
            job: components["schemas"]["RealtimeJobResponse"] | null;
            snapshot: components["schemas"]["RealtimeSnapshotResponse"] | null;
            /** Cooldown Until */
            cooldown_until: string | null;
        };
        /** ReportRequest */
        ReportRequest: {
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /** Template Version */
            template_version: string;
            /** Report Version */
            report_version: number;
            /** Content */
            content: string;
        };
        /** RuleVersionRequest */
        RuleVersionRequest: {
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Confirm Recalculate */
            confirm_recalculate: boolean;
        };
        /** RuleVersionResponse */
        RuleVersionResponse: {
            /** Id */
            id: number;
            /** Version */
            version: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Requires Recalculation */
            requires_recalculation: boolean;
        };
        /** ScreeningRequest */
        ScreeningRequest: {
            /**
             * Minimum Score
             * @default 0
             */
            minimum_score: number;
            /** Markets */
            markets?: string[];
            /** Pct Change Min */
            pct_change_min?: number | null;
            /** Pct Change Max */
            pct_change_max?: number | null;
            /** Volume Ratio Min */
            volume_ratio_min?: number | null;
            /** Close Above Ma20 */
            close_above_ma20?: boolean | null;
            /** Ma5 Above Ma20 */
            ma5_above_ma20?: boolean | null;
            /** Macd Filters */
            macd_filters?: string[];
            /** Rsi Min */
            rsi_min?: number | null;
            /** Rsi Max */
            rsi_max?: number | null;
            /**
             * Include St
             * @default false
             */
            include_st: boolean;
            /**
             * Include Suspended
             * @default false
             */
            include_suspended: boolean;
            /** Minimum Listed Days */
            minimum_listed_days?: number | null;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
        };
        /** ScreeningResponse */
        ScreeningResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Items */
            items: components["schemas"]["CandidateItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Auto Sync Enabled */
            auto_sync_enabled: boolean;
            /** Auto Sync Time */
            auto_sync_time: string;
            /** Adapter Version */
            adapter_version: string;
            /** Current Rule Version */
            current_rule_version: string;
            /** Indicator Parameters */
            indicator_parameters: {
                [key: string]: number;
            };
            /** Last Successful Batch */
            last_successful_batch: string | null;
            /** Completeness Rate */
            completeness_rate: number | null;
            /** Failed Jobs */
            failed_jobs: {
                [key: string]: unknown;
            }[];
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Auto Sync Enabled */
            auto_sync_enabled: boolean;
            /** Auto Sync Time */
            auto_sync_time: string;
        };
        /** SignalItem */
        SignalItem: {
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Rule Code */
            rule_code: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** SignalSeriesResponse */
        SignalSeriesResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Items */
            items: components["schemas"]["SignalItem"][];
        };
        /** StockCandidateOutcomeItem */
        StockCandidateOutcomeItem: {
            /** Horizon Trading Days */
            horizon_trading_days: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "COMPLETED" | "UNAVAILABLE";
            /** Reference Trade Date */
            reference_trade_date: string | null;
            /** Evaluation Trade Date */
            evaluation_trade_date: string | null;
            /**
             * Expected Evaluation Trade Date
             * @description 由完整权威交易日历确定的预计评价日；不代表评价已完成
             */
            expected_evaluation_trade_date: string | null;
            /** Reference Price */
            reference_price: number | null;
            /** Evaluation Price */
            evaluation_price: number | null;
            /** Return Rate */
            return_rate: number | null;
            /** Mfe */
            mfe: number | null;
            /** Mae */
            mae: number | null;
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /** Calculation Version */
            calculation_version: string;
        };
        /** StockDetailResponse */
        StockDetailResponse: {
            /**
             * Source
             * @default unknown
             */
            source: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Batch Id */
            batch_id: number;
            /** Rule Version */
            rule_version: string;
            /** Batch Status */
            batch_status: string;
            /** Risk Acknowledged */
            risk_acknowledged: boolean;
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name: string;
            /** Industry */
            industry: string | null;
            price: components["schemas"]["PriceItem"] | null;
            /** Trend */
            trend: string;
            /** Risk Level */
            risk_level: string;
            /** Risk Reasons */
            risk_reasons: string[];
            /** Candidate Outcomes */
            candidate_outcomes: components["schemas"]["StockCandidateOutcomeItem"][];
        };
        /** StrategyOutcomeFilters */
        StrategyOutcomeFilters: {
            /** Rule Version */
            rule_version: string | null;
            /** Latest Trading Days */
            latest_trading_days: number | null;
            /** Horizon */
            horizon: number | null;
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Status */
            status: string | null;
        };
        /** StrategyOutcomePage */
        StrategyOutcomePage: {
            /** Items */
            items: components["schemas"]["StrategyOutcomeView"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Calculation Version */
            calculation_version: string;
            filters: components["schemas"]["StrategyOutcomeFilters"];
            /** Data Date */
            data_date: string | null;
        };
        /** StrategyOutcomeSummary */
        StrategyOutcomeSummary: {
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Unavailable */
            unavailable: number;
            /** Pending */
            pending: number;
            /** Sample Size */
            sample_size: number;
            /** Completion Rate */
            completion_rate: number;
            /** Mean Return Rate */
            mean_return_rate: number | null;
            /** Median Return Rate */
            median_return_rate: number | null;
            /** Positive Return Ratio */
            positive_return_ratio: number | null;
            /** Mean Mfe */
            mean_mfe: number | null;
            /** Mean Mae */
            mean_mae: number | null;
            /**
             * Max Drawdown Approx
             * @description COMPLETED 样本持有窗口 MAE 的最差值（最小值，负百分数）；仅为样本级近似，不是资金曲线最大回撤
             */
            max_drawdown_approx: number | null;
            /** Insufficient Sample */
            insufficient_sample: boolean;
            /** Calculation Version */
            calculation_version: string;
            filters: components["schemas"]["StrategyOutcomeFilters"];
            /** Data Date */
            data_date: string | null;
        };
        /** StrategyOutcomeView */
        StrategyOutcomeView: {
            /** Id */
            id: number;
            /** Candidate Result Id */
            candidate_result_id: number;
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name: string | null;
            /** Source Batch Id */
            source_batch_id: number;
            /** Evaluation Batch Id */
            evaluation_batch_id: number | null;
            /**
             * Source Trade Date
             * Format: date
             */
            source_trade_date: string;
            /** Rule Version */
            rule_version: string;
            /** Horizon Trading Days */
            horizon_trading_days: number;
            /** Reference Trade Date */
            reference_trade_date: string | null;
            /** Evaluation Trade Date */
            evaluation_trade_date: string | null;
            /**
             * Expected Evaluation Trade Date
             * @description 由完整权威交易日历确定的预计评价日；不代表评价已完成
             */
            expected_evaluation_trade_date: string | null;
            /** Reference Price */
            reference_price: number | null;
            /** Evaluation Price */
            evaluation_price: number | null;
            /** Return Rate */
            return_rate: number | null;
            /** Mfe */
            mfe: number | null;
            /** Mae */
            mae: number | null;
            /** Status */
            status: string;
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /** Calculation Version */
            calculation_version: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SyncCreatedResponse */
        SyncCreatedResponse: {
            /** Job Id */
            job_id: number;
            /** Batch Id */
            batch_id: number;
        };
        /** SyncJobResponse */
        SyncJobResponse: {
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number | null;
            /** Target Trade Date */
            target_trade_date: string | null;
            /** Status */
            status: string;
            /** Stage */
            stage: string;
            /** Progress */
            progress: number;
            /** Completed Count */
            completed_count: number;
            /** Failed Count */
            failed_count: number;
            /** Failed Items */
            failed_items: string[];
            /** Error Summary */
            error_summary: string | null;
        };
        /** SyncRequest */
        SyncRequest: {
            /** Target Trade Date */
            target_trade_date?: string | null;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            active_batch: components["schemas"]["BatchContext"] | null;
            latest_sync: components["schemas"]["SyncJobResponse"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistGroupItem */
        WatchlistGroupItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Sort Order */
            sort_order: number;
        };
        /** WatchlistGroupResponse */
        WatchlistGroupResponse: {
            /** Items */
            items: components["schemas"]["WatchlistGroupItem"][];
        };
        /** WatchlistItemResponse */
        WatchlistItemResponse: {
            /** Id */
            id: number;
            /** Group Id */
            group_id: number;
            /** Group Name */
            group_name?: string | null;
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name?: string | null;
            /** Note */
            note: string | null;
            /** Trade Date */
            trade_date?: string | null;
            /** Close */
            close?: number | null;
            /** Pct Change */
            pct_change?: number | null;
            /**
             * Signal Codes
             * @default []
             */
            signal_codes: string[];
            /** Risk Level */
            risk_level?: string | null;
            /**
             * Alert Status
             * @default UNTRIGGERED
             */
            alert_status: string;
            realtime?: components["schemas"]["RealtimeQuoteResponse"] | null;
            ai_analysis?: components["schemas"]["AIRecommendationItem"] | null;
        };
        /** WatchlistRequest */
        WatchlistRequest: {
            /** Group Id */
            group_id: number;
            /** Market */
            market: string;
            /** Stock Code */
            stock_code: string;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /** Items */
            items: components["schemas"]["WatchlistItemResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    import_ai_recommendations_api_v1_ai_recommendations_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIRecommendationImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIRecommendationImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    create_sync_job_api_v1_sync_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_sync_job_api_v1_sync_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sync_job_api_v1_sync_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_data_batch_api_v1_data_batches__batch_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchActivationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchActivationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    stock_detail_api_v1_stocks__market___stock_code__get: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: never;
            path: {
                market: string;
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_prices_api_v1_stocks__market___stock_code__prices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_indicators_api_v1_stocks__market___stock_code__indicators_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_signals_api_v1_stocks__market___stock_code__signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screenings_api_v1_screenings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreeningRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_items_api_v1_watchlist_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
        };
    };
    create_watchlist_item_api_v1_watchlist_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_groups_api_v1_watchlist_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistGroupResponse"];
                };
            };
        };
    };
    delete_watchlist_item_api_v1_watchlist_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
                watchlist_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_alert_api_v1_alerts__signal_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_v1_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_v1_reports__report_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_v1_screener_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetList"];
                };
            };
        };
    };
    create_preset_api_v1_screener_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_preset_api_v1_screener_presets__preset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preset_api_v1_screener_presets__preset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    default_preset_api_v1_screener_presets__preset_id__default_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_api_v1_decision_notes_get: {
        parameters: {
            query?: {
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_v1_decision_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_v1_decision_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_v1_decision_notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_note_api_v1_decision_notes__note_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_version_api_v1_rule_versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alert_rules_api_v1_alert_rules_get: {
        parameters: {
            query?: {
                include_history?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_rule_api_v1_alert_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_rule_api_v1_alert_rules__logical_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logical_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_rule_api_v1_alert_rules__logical_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logical_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_realtime_refresh_post: {
        parameters: {
            query?: {
                scope?: "watchlist";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_realtime_status_get: {
        parameters: {
            query?: {
                scope?: "watchlist";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quotes_api_v1_realtime_quotes_get: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                page_size?: number;
                scope?: "watchlist";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeQuotesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outcomes_api_v1_strategy_outcomes_get: {
        parameters: {
            query?: {
                rule_version?: string | null;
                latest_trading_days?: number | null;
                horizon?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                status?: ("PENDING" | "COMPLETED" | "UNAVAILABLE") | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOutcomePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_outcomes_api_v1_strategy_outcomes_summary_get: {
        parameters: {
            query?: {
                rule_version?: string | null;
                latest_trading_days?: number | null;
                horizon?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                status?: ("PENDING" | "COMPLETED" | "UNAVAILABLE") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOutcomeSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_outcomes_api_v1_strategy_outcomes__candidate_result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_result_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOutcomes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outcome_run_api_v1_strategy_outcome_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outcome_run_api_v1_strategy_outcome_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
