"""initial_schema

Revision ID: 5f02a932346b
Revises:
Create Date: 2026-08-25 15:14:51.705188
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5f02a932346b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_batch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("completeness_rate", sa.Float(), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_batch_is_active"), "data_batch", ["is_active"], unique=False)
    op.create_index(op.f("ix_data_batch_trade_date"), "data_batch", ["trade_date"], unique=False)
    op.create_index(
        "uq_data_batch_active",
        "data_batch",
        ["is_active"],
        unique=True,
        sqlite_where=sa.text("is_active = 1"),
    )
    op.create_table(
        "decision_note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_note_stock_code"), "decision_note", ["stock_code"], unique=False
    )
    op.create_table(
        "screener_preset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "stock_basic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("stock_name", sa.String(length=64), nullable=False),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("list_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "stock_code"),
    )
    op.create_table(
        "sync_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["data_batch.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_job_batch_id"), "sync_job", ["batch_id"], unique=False)
    op.create_table(
        "system_setting",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "trade_calendar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "trade_date"),
    )
    op.create_table(
        "watchlist_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "analysis_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("template_version", sa.String(length=32), nullable=False),
        sa.Column("report_version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["data_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "batch_id",
            "market",
            "stock_code",
            "trade_date",
            "rule_version",
            "template_version",
            "report_version",
        ),
    )
    op.create_index(
        op.f("ix_analysis_report_batch_id"), "analysis_report", ["batch_id"], unique=False
    )
    op.create_table(
        "candidate_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("positive_event_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("volume_ratio", sa.Float(), nullable=True),
        sa.Column("pct_change", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["data_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "market", "stock_code"),
    )
    op.create_index(
        op.f("ix_candidate_result_batch_id"), "candidate_result", ["batch_id"], unique=False
    )
    op.create_table(
        "daily_indicator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["data_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "market", "stock_code", "trade_date", "rule_version"),
    )
    op.create_index(
        op.f("ix_daily_indicator_batch_id"), "daily_indicator", ["batch_id"], unique=False
    )
    op.create_table(
        "daily_price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("adjustment", sa.String(length=8), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("pct_change", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["data_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "market", "stock_code", "trade_date", "adjustment"),
    )
    op.create_index(op.f("ix_daily_price_batch_id"), "daily_price", ["batch_id"], unique=False)
    op.create_index(op.f("ix_daily_price_stock_code"), "daily_price", ["stock_code"], unique=False)
    op.create_index(op.f("ix_daily_price_trade_date"), "daily_price", ["trade_date"], unique=False)
    op.create_table(
        "index_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("index_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("pct_change", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["data_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "index_code", "trade_date"),
    )
    op.create_index(op.f("ix_index_daily_batch_id"), "index_daily", ["batch_id"], unique=False)
    op.create_table(
        "signal_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("rule_code", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["data_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "stock_code", "trade_date", "rule_code", "rule_version"),
    )
    op.create_index(op.f("ix_signal_event_batch_id"), "signal_event", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_signal_event_stock_code"), "signal_event", ["stock_code"], unique=False
    )
    op.create_table(
        "watchlist_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["watchlist_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "stock_code"),
    )
    op.create_index(
        op.f("ix_watchlist_item_group_id"), "watchlist_item", ["group_id"], unique=False
    )
    op.create_table(
        "alert_event_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_event_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["signal_event_id"],
            ["signal_event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_event_state_signal_event_id"),
        "alert_event_state",
        ["signal_event_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alert_event_state_signal_event_id"), table_name="alert_event_state")
    op.drop_table("alert_event_state")
    op.drop_index(op.f("ix_watchlist_item_group_id"), table_name="watchlist_item")
    op.drop_table("watchlist_item")
    op.drop_index(op.f("ix_signal_event_stock_code"), table_name="signal_event")
    op.drop_index(op.f("ix_signal_event_batch_id"), table_name="signal_event")
    op.drop_table("signal_event")
    op.drop_index(op.f("ix_index_daily_batch_id"), table_name="index_daily")
    op.drop_table("index_daily")
    op.drop_index(op.f("ix_daily_price_trade_date"), table_name="daily_price")
    op.drop_index(op.f("ix_daily_price_stock_code"), table_name="daily_price")
    op.drop_index(op.f("ix_daily_price_batch_id"), table_name="daily_price")
    op.drop_table("daily_price")
    op.drop_index(op.f("ix_daily_indicator_batch_id"), table_name="daily_indicator")
    op.drop_table("daily_indicator")
    op.drop_index(op.f("ix_candidate_result_batch_id"), table_name="candidate_result")
    op.drop_table("candidate_result")
    op.drop_index(op.f("ix_analysis_report_batch_id"), table_name="analysis_report")
    op.drop_table("analysis_report")
    op.drop_table("watchlist_group")
    op.drop_table("trade_calendar")
    op.drop_table("system_setting")
    op.drop_index(op.f("ix_sync_job_batch_id"), table_name="sync_job")
    op.drop_table("sync_job")
    op.drop_table("stock_basic")
    op.drop_table("screener_preset")
    op.drop_index(op.f("ix_decision_note_stock_code"), table_name="decision_note")
    op.drop_table("decision_note")
    op.drop_index(
        "uq_data_batch_active", table_name="data_batch", sqlite_where=sa.text("is_active = 1")
    )
    op.drop_index(op.f("ix_data_batch_trade_date"), table_name="data_batch")
    op.drop_index(op.f("ix_data_batch_is_active"), table_name="data_batch")
    op.drop_table("data_batch")
    # ### end Alembic commands ###
